# ============================================================
#   SITE CONFIGURATION
#   Adapted for roboticslaburjc/2025-tfg-carlos-iglesias
# ============================================================

# --------------------------
# Theme and plugins
# --------------------------
remote_theme: cotes2020/jekyll-theme-chirpy
plugins:
  - jekyll-remote-theme

# --------------------------
# Site settings
# --------------------------
lang: es
timezone: Europe/Madrid

title: Carlos Iglesias Puerta
tagline: Estudiante de Ingeniería de Robótica Software en la Universidad Rey Juan Carlos
description: >-
  Trabajo Fin de Grado — Universidad Rey Juan Carlos. Proyecto de Robótica Software.

# URL base del sitio (sin / al final)
url: "https://roboticslaburjc.github.io"
# Carpeta donde vive el sitio dentro del repo
baseurl: "/2025-tfg-carlos-iglesias"

# --------------------------
# Social & SEO
# --------------------------
github:
  username: roboticslaburjc

twitter:
  username: twitter_username

social:
  name: Carlos Iglesias Puerta
  email: cigleasiapuerta@gmail.com
  links:
    - https://github.com/HectorMartinezCabezas
    - https://twitter.com/username

webmaster_verifications:
  google:
  bing:
  yandex:

# --------------------------
# Analytics (optional)
# --------------------------
analytics:
  google:
    id: # UA-XXXXX-Y
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# --------------------------
# Appearance
# --------------------------
theme_mode: # [light | dark]
avatar: "logo.png"
social_preview_image:
toc: true

# --------------------------
# Comments (optional)
# --------------------------
comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:

# --------------------------
# Assets
# --------------------------
assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

paginate: 10

# --------------------------
# Markdown and formatting
# --------------------------
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
  - node_modules

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
