# frozen_string_literal: true

source "https://rubygems.org"

# Jekyll y tema Chirpy
gem "jekyll", "~> 4.3"
gem "jekyll-theme-chirpy", "~> 6.5", ">= 6.5.5"

# Para pruebas de HTML
gem "html-proofer", "~> 4.4", group: :test

# Dependencias opcionales para Windows
platforms :windows do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
  gem "wdm", "~> 0.1.1"
end

